/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuPrincipalController;

/**
 *
 * @author Samuel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemServiço = new javax.swing.JMenuItem();
        jMenuOperação = new javax.swing.JMenu();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        jMenuRelatório = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel\\Dropbox\\My PC (LAPTOP-19T3V1ND)\\Documents\\NetBeansProjects\\BarberShop\\src\\main\\java\\View\\imagens\\fundo-MenuPrincipal.jpg")); // NOI18N

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel\\Dropbox\\My PC (LAPTOP-19T3V1ND)\\Documents\\NetBeansProjects\\BarberShop\\src\\main\\java\\View\\imagens\\icons\\cliente32-icon.png")); // NOI18N
        jMenuItemClientes.setText("Clientes");
        jMenuCadastro.add(jMenuItemClientes);

        jMenuItemServiço.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemServiço.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel\\Dropbox\\My PC (LAPTOP-19T3V1ND)\\Documents\\NetBeansProjects\\BarberShop\\src\\main\\java\\View\\imagens\\icons\\tesoura32-icon.png")); // NOI18N
        jMenuItemServiço.setText("Serviço");
        jMenuItemServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServiçoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemServiço);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperação.setText("Operação");
        jMenuOperação.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/agenda32-icon.png"))); // NOI18N
        jMenuItemAgenda.setText("Agenda");
        jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaActionPerformed(evt);
            }
        });
        jMenuOperação.add(jMenuItemAgenda);

        jMenuBar1.add(jMenuOperação);

        jMenuRelatório.setText("Relatório");
        jMenuRelatório.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenuRelatório);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServiçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemServiçoActionPerformed

    private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed
        // TODO add your handling code here:
        controller.navegarParaAgenda();
    }//GEN-LAST:event_jMenuItemAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemServiço;
    private javax.swing.JMenu jMenuOperação;
    private javax.swing.JMenu jMenuRelatório;
    // End of variables declaration//GEN-END:variables
}
